### ISSUE TITLE
Windows Compatability

### ISSUE THREAD

**Issue by NoelJacob** [deus0ww/mpv-conf#1]
The Files doesn't seem to work on Windows. I've tried changing the profile under [default] to pc and also then to win and finally with all macos commands removed. But still no avail.

**Comment by Tsubajashi** [comment]
What exactly isn’t working? I have tested it a little while ago and it worked.

**Comment by deus0ww** [comment]
What's failing? A log file would help.  How to: https://mpv.io/manual/master/#options-log-file

I should note that this repo is mainly for customizing MPV for my personal Macs. The Windows settings are minimally tested on a virtual machine but they should work.  Also, I'm using git HEAD of MPV so, at the very least, you should be on the newest release version (v.0.32, I think) to use my settings.
