### ISSUE TITLE
`Thumbnailer.lua`

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#12]
If `auto_gen=no`, it seems to be no diff to use the `script-message-to Thumbnailer Thumbnailer-start` or `script-message-to Thumbnailer Thumbnailer-toggle-gen` at runtime. When mpv switched to another video in the playlist, it cannot generate the thumbs. Is it a bug?

The similar situation also happened on the another option —— `auto_show=no` .... `script-message-to Thumbnailer Thumbnailer-toggle-osc` work as the same with `script-message-to Thumbnailer Thumbnailer-show`

**Comment by deus0ww** [comment]
I'm not sure what you're asking. The options set the defaults for when you open a file. The script messages allows you to take action when the file is already opened.

**Comment by hooke007** [comment]
If I set `a script-message-to Thumbnailer Thumbnailer-toggle-gen` in input.conf, I can let it automatically generate the thumbs again. It do work as my expectation at the first video. But when mpv goes to the second video in the playlist, it recovered to the `auto_gen=no`, I have to click `a` again to generate.

**Comment by hooke007** [comment]
I don't change this option https://mpv.io/manual/master/#options-reset-on-next-file
Maybe it's the limitation of mpv itself?

**Comment by deus0ww** [comment]
That's working as expected. On file opening, the configuration is reset to whatever is set in the script options. You can change the script option at runtime to do what I think you want to do. I think the command is:

change-list script-opts append Thumbnailer-auto_gen=yes

**Comment by hooke007** [comment]
>change-list script-opts append Thumbnailer-auto_gen=yes

Thanks, I know how to make it work perfectly.
