### ISSUE TITLE
[Thumbnailer.lua] delete_cache_dir has problem with multi instance

### ISSUE THREAD

**Issue by zhongfly** [deus0ww/mpv-conf#15]
When I open two video windows and create thumbnails, if one video window is closed, the thumbnails of the other video that is not closed will also be deleted.

**Comment by zhongfly** [comment]
I think we can change the line 188 to:
```
local default_cache_dir  = join_paths(OPERATING_SYSTEM == OS_WIN and os.getenv('TEMP') or '/tmp/', script_name,tostring(os.time()))
```

**Comment by deus0ww** [comment]
There's a use-case for not auto-deleting and reusing the cache, which the above solution will break. I'd recommend that you disable auto_delete and deal with it manually.

**Comment by zhongfly** [comment]
> There's a use-case for not auto-deleting and reusing the cache, which the above solution will break. I'd recommend that you disable auto_delete and deal with it manually.

I see. It seems that this problem can't be solved simply

**Comment by zhongfly** [comment]
I came up with a new method to use an empty file named process ID as a file lock. Before deleting, make sure that no other process locks the folder.

When creating a cache folder, place a file lock (named pid) in the thumbnail folder of each video and also in the root folder
1. auto_delete =1：When the file is closing after watching, delete the lock of the process, check if there is no lock, then delete a thumbnail folder.
2. auto_delete =2：When you close the player, delete the lock of this process, check if there is no lock in the root folder, and delete the entire cache folder
