### ISSUE TITLE
Q: Thumbnail scripts differences?

### ISSUE THREAD

**Issue by polarathene** [deus0ww/mpv-conf#18]
There is not much information about your thumbnail scripts here, or elsewhere online. Just curious how they differ from https://github.com/marzzzello/mpv_thumbnail_script , did you choose to write/maintain your own alternative?

**Comment by deus0ww** [comment]
Reasons:
- I didn't like the looks of the other ones especially when there's a progress bar
- More options (slow start, delays, rotation, dynamic number of thumbnails based on bitrate, etc )
- More up-to-date with the default mpv osc
- Performance optimization for my setup
- It was fun

**Comment by polarathene** [comment]
> * More up-to-date with the default mpv osc (could be problematic if you're not using mpv git master)

The linked repo is actively maintained, it's behind 1 commit for the upstream git OSC at present. But seems more accessible to use beyond that due to clearer separation (vs mixed in with various other config and scripts), and an associated README for docs.

---

Thanks for the response.

I assume due to lack of separation into it's own project and documentation, that it's intended for your personal usage only, others are welcome to use it but you're not interested in making it a more discoverable as an alternative solution? (_Totally fine, I can relate. Docs can seem otherwise unnecessary, and supporting users isn't fun or worth the time_)

**Comment by deus0ww** [comment]
> I assume due to lack of separation into it's own project and documentation, that it's intended for your personal usage only, others are welcome to use it but you're not interested in making it a more discoverable as an alternative solution? (_Totally fine, I can relate. Docs can seem otherwise unnecessary, and supporting users isn't fun or worth the time_)

Yeah, this repo exists to fulfill my OCD-like need for the perfect mpv setup, and to keep config synced between my various machines. I kept it public in case others find it useful but that's as much discoverability as I'm willing to go. 

I'll certainly try to fix any issue that doesn't conflict with my needs as I have done in the past but you shouldn't have a high expectation for it.

As for documentations, I'm too unmotivated to write a readme but the script options should be sufficiently documented in the code.

**Comment by pintassilgo** [comment]
Reusing this Q thread, of course not requesting anything, just a honest question:

I think PotPlayer (closed source and Windows only) has the most *perfect* preview-on-seek system, it's incredibly smooth. Unlike mpv thumb scripts, PotPlayer seems to work on demand on mouseover: you hover at seekbar, then PotPlayer instantly processes the thumb at that specific time then shows it. It's so fast I can't even notice the delay before showing the preview.

It would be impossible with current mpv API for a script to do the same? Of course I don't know the internals, just a honest lame question. Because I guess it would be much more efficient than current model of processing all previews "at once" even that most will never be requested to display.

I guess It would be much less resource intensive and also more accurate, because currently if you try to seek before workers finish their job, the thumb may be a little too far from actual preview at that seek time.

Anyway, thanks for sharing your work, I use your script.

**Comment by deus0ww** [comment]
> Reusing this Q thread, of course not requesting anything, just a honest question:
> 
> I think PotPlayer (closed source and Windows only) has the _perfect_ preview-on-seek system, it's incredibly smooth. Unlike mpv thumb scripts, PotPlayer seems to work on demand on mousemove: you hover the seekbar, then PotPlayer instantly processes the thumb at that specific time and shows it. It's so fast I can't even notice the delay before showing the preview.
> 
> It would be impossible with current mpv API for a script to do the same? I don't know the internals, just a honest lame question. Because I guess it would be much more efficient than current model of processing all previews "at once" even that most of them will never be requested to display.
> 
> I guess It would be much less resource intensive and also more accurate, because currently if you try to seek before workers finish their job, the thumb may be a little too far from actual preview at the hovered seek range.
> 
> Anyway, thanks for sharing your work, I use your script.

That functionality is certainly within the capability of mpv but not my script, and I have no plan to implement it. Being able to scrub the progress bar with almost zero latency is important to me, especially for non-local media (like youtube, for example).

**Comment by pintassilgo** [comment]
> That functionality is certainly within the capability of mpv

Good to know, thanks.

> Being able to scrub the progress bar with almost zero latency

PotPlayer is like that. I don't know how it works, it's amazing. It's instant just like YouTube web thumbs system, except that
1. YouTube loads low resolution thumbs first, then a few seconds later it serves a better quality (but still small, 160px if I'm not mistaken). PotPlayer thumbs has good quality from the start.
2. YouTube stores thumbs in big image grids with 100 thumbs in each, PotPlayer needs to generate the thumbs on the fly and somehow it does that instantly and without any hiccups, it's smooth like if all thumbs were cached from the beginning.

Just one last question about mpv capability: is it possible to store thumbs on memory or it's required to write on disk as your script does?

**Comment by deus0ww** [comment]
> Just one last question about mpv capability: is it possible to store thumbs on memory or it's required to write on disk as your script does?

https://mpv.io/manual/master/#command-interface-overlay-add
