### ISSUE TITLE
thumbnailer_worker could not be found

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#19]
https://github.com/mpv-player/mpv/commit/84821dbcb6d9e16b8f11da2135208e4f3e66fcd0 After this commit, thumbnailer could not work in Windows.

![Snipaste_2022-03-24_13-22-57](https://user-images.githubusercontent.com/41094733/159927822-9fc3aeb7-73a7-44e5-80df-28bf983879a1.jpg)

**Comment by deus0ww** [comment]
This is too low-level for me to understand/fix.  See: https://github.com/mpv-player/mpv/issues/10007

**Comment by hooke007** [comment]
Is [it](https://www.lua.org/manual/5.1/manual.html#:~:text=If%20the%20function%20was%20defined%20in%20a%20string%2C%20then%20source%20is%20that%20string.%20If%20the%20function%20was%20defined%20in%20a%20file%2C%20then%20source%20starts%20with%20a%20%27%40%27%20followed%20by%20the%20file%20name.) possible to help understand?

**Comment by deus0ww** [comment]
I may have fixed it... please test.

**Comment by hooke007** [comment]
Excellent.

A off-topic question:
Is it possible not to output the error mssage from ffmpeg?(Even though it generated thumbs successfully.)
![Snipaste_2022-03-24_16-32-57](https://user-images.githubusercontent.com/41094733/159965543-d938fe79-f40c-4639-9066-16927bd0f622.jpg)

**Comment by deus0ww** [comment]
I don't know. I don't have any media file that cause that warning from ffmpeg.
