### ISSUE TITLE
mcp 2012 running on catalina (Error parsing option and unable to run scripts)

### ISSUE THREAD

**Issue by rayanke** [deus0ww/mpv-conf#2]
whenever i start mpv these errors show up not sure how to fix it
Error parsing option icc-cache-dir (option not found)
/Users/rayan/.config/mpv/mpv.conf:26: setting option icc-cache-dir='/Users/Shared/Library/Caches/mpv/icc/' failed.
Error parsing option zimg-fast (option not found)
/Users/rayan/.config/mpv/mpv.conf:39: setting option zimg-fast='no' failed.
Error parsing option zimg-scaler (option not found)
/Users/rayan/.config/mpv/mpv.conf:40: setting option zimg-scaler='spline36' failed.
Error parsing option zimg-scaler-chroma (option not found)
/Users/rayan/.config/mpv/mpv.conf:41: setting option zimg-scaler-chroma='spline36' failed.
Error parsing option osc (option not found)
/Users/rayan/.config/mpv/mpv.conf:147: setting option osc='no' failed.
Error parsing option load-stats-overlay (option not found)
/Users/rayan/.config/mpv/mpv.conf:148: setting option load-stats-overlay='no' failed.
Error parsing option ytdl-raw-options-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:179: setting option ytdl-raw-options-append='sub-lang="th,tha,thTH,th-TH,en,eng,enUS,en-US"' failed.
Error parsing option ytdl-raw-options-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:180: setting option ytdl-raw-options-append='write-sub=' failed.
Error parsing option ytdl-raw-options-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:181: setting option ytdl-raw-options-append='write-auto-sub=' failed.
Error parsing option icc-3dlut-size (option not found)
/Users/rayan/.config/mpv/mpv.conf:325: setting option icc-3dlut-size='256x256x256' failed.
Error parsing option icc-contrast (option not found)
/Users/rayan/.config/mpv/mpv.conf:326: setting option icc-contrast='1000' failed.
Error parsing option icc-profile-auto (option not found)
/Users/rayan/.config/mpv/mpv.conf:327: setting option icc-profile-auto='yes' failed.
Error parsing option script-opts-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:381: setting option script-opts-append='Shaders-enabled=no' failed.
Error parsing option script-opts-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:390: setting option script-opts-append='Shaders-enabled=no' failed.
Error parsing option script-opts-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:399: setting option script-opts-append='Shaders-enabled=no' failed.
Error parsing option script-opts-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:408: setting option script-opts-append='Shaders-enabled=yes' failed.
Error parsing option script-opts-append (option not found)
/Users/rayan/.config/mpv/mpv.conf:426: setting option script-opts-append='Mac_Window-display_w=2560' failed.
/Users/rayan/.config/mpv/mpv.conf: too many errors, stopping.
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Thumbnailer.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Misc.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Test.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Filter_Audio_ScaleTempo.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Filter_Video.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Thumbnailer_OSC.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Tagger.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Shaders.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Equalizer_Profiles.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/zones.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Thumbnailer_Worker.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Mac_Integration.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Filter_Audio.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Subliminal.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Mac_Window.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Language_Switcher.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Filter_Manager.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/Mac_Host_Profile.lua
Can't load unknown script: /Users/rayan/.config/mpv/scripts/stats.lua

**Comment by deus0ww** [comment]
You need to build mpv from git master.
