### ISSUE TITLE
osc always try to show the thumbnail with ignoring the options.

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#20]
```
auto_gen=no
auto_show=no
```
It seems doesn't work now.

**Comment by hooke007** [comment]
I reverted https://github.com/deus0ww/mpv-conf/commit/cc10823a0a9340fb58717e66cbbe37f2e05b27aa here to fix the issue.

**Comment by dexeonify** [comment]
I use both of the options daily and they seem to work:
- Thumbnails are not automatically generated
- Thumbnailer OSC is not showed by default

However, now `auto_show=yes` doesn't show Thumbnailer OSC by default. Reverting that commit also fixes the issue.

**Comment by deus0ww** [comment]
Please test, again.

**Comment by dexeonify** [comment]
Nope, that didn't fix it for me. BTW, I applied the commits incorrectly previously. Now I'm getting the same issue as OP with `auto_show=no`.

**Comment by deus0ww** [comment]
How are you setting those options (in conf file, in mpv.conf, by script, etc)?

**Comment by dexeonify** [comment]
In the conf file, and uncommenting the following:
```properties
auto_gen=no
auto_show=no
```

My set-up is a bit complicated as I use a modded custom OSC to work with your Thumbnailer.
But that's not the cause of the problem, because I tested your scripts in a minimal environment:
- No other scripts
- All 3 thumbnailer scripts under `scripts/`
- `thumbnailer.conf` is under `script-opts/`
- All of them freshly taken from your git repo

**Comment by dexeonify** [comment]
Pretty sure this is cause of the problem:
https://github.com/deus0ww/mpv-conf/blob/e0fa8fb494571c4e241ed0c178fab23c56ead3ce/scripts/Thumbnailer.lua#L622

It will always show the thumbnailer OSC if all the checks above succeeded. Removing it fixes the issue.

**Comment by deus0ww** [comment]
Thanks for that but I'm just going to revert the recent changes, which was to fix issues when switching between audio and video files.

This script is overdue for a major rewrite anyway. (This was my first Lua script... a big pile of spaghetti code...)

**Comment by hooke007** [comment]
Close it for the temporary fix.
