### ISSUE TITLE
[feature request] To avoid the multi-regeneration of thumbs

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#22]
If these options were set with different values, each time of cycling fullscreen would lead to regenerate thumbnails.
```
scalewindowed=
scalefullscreen=
scaleforcedwindow=
```

**Comment by deus0ww** [comment]
Changing those values changes the size of the thumbnails in their respective modes. MPV can't scale the thumbnail bitmaps so they have to be regenerated.

**Comment by hooke007** [comment]
Or possible to temporarily keep the cache? So that it only needs to generate thumbs at most twice in one session.

**Comment by hooke007** [comment]
Re-considering that it is not an immediate need, close it.

**Comment by deus0ww** [comment]
what's your auto_delete setting?
