### ISSUE TITLE
[noob q] Command-line invocation for lua script

### ISSUE THREAD

**Issue by cg-cri-gl** [deus0ww/mpv-conf#24]
This is a newbee question, please don't shoot ! :) 

The lua script in question is [Filter_Audio.lua](https://github.com/deus0ww/mpv-conf/blob/master/scripts/Filter_Audio.lua) . 
The goal is trying to use a specific filter (iiuc the code adds several new audio filters) like  _DenoiseAudio_ for example.

This isn't working:

`mpv --script=Filter_Audio.lua --af  DenoiseAudio  1.mp3 
`

Tried 
`mpv --script=Filter_Audio.lua --af  Filter_Audio-DenoiseAudio  1.mp3 
`
also,... no joy.

The (obvious by now) question is : how to run mpv by selecting a specifc filter (or several) from the script - or , even better - toggle on / off in a circular fashion through all of the filters (during playback ) ? 

The bonus questions :)
-  how would one build the mpv command line by calling the _ffmpeg_ filters directly, i.e. '`mpv ... --af= '? or / and 'mpv --lavfi=...' `  for various filters?
- (in a more general note) The end-goal for me is to liste to some very bad voice recording ; _bad_ meaning'big room' effect / distant speaker , or simply low-quality mic.. not sure... fact is at least 2 filters would be needed: volume normalize + 'voice' enhancement.

Thanks !

**Comment by deus0ww** [comment]
If you want to use my filter scripts, use script options and keybindings to control it. 

If you want to use mpv built-in filter options, then do that. See: https://mpv.io/manual/master/#options-af

The script is just a wrapper around mpv's built-in functionality.  Mixing the syntax is not going to work.

**Comment by cg-cri-gl** [comment]
Thanks, understood.

Where can i find some instructions / examples how to do what you said ?  
> If you want to use my filter scripts, use script options and keybindings to control it.

Also, is my understanding correct that when using _--script-x_  options, one cannot select a specific filter from the mentioned [Filter_Audio.lua](https://github.com/deus0ww/mpv-conf/blob/master/scripts/Filter_Audio.lua)  file ? The only was is to cycle-through the filters therein via key-presses? 

T y

**Comment by deus0ww** [comment]
> Where can i find some instructions / examples how to do what you said ?

https://mpv.io/manual/master/#audio-filters
https://mpv.io/manual/master/#command-interface

> Also, is my understanding correct that when using _--script-x_ options, one cannot select a specific filter from the mentioned [Filter_Audio.lua](https://github.com/deus0ww/mpv-conf/blob/master/scripts/Filter_Audio.lua) file ? The only was is to cycle-through the filters therein via key-presses?

Correct
