### ISSUE TITLE
the artifacts of cfl_lite

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#26]
It could also be easily observed by the another widely used [test-img]( https://github.com/hooke007/MPV_lazy/blob/obs/Temp/IMG/chroma-420.jpg).

raw:
![Snipaste_2023-11-04_15-35-22](https://github.com/deus0ww/mpv-conf/assets/41094733/36eb2532-0f0e-4bfe-a21d-7d0807633757)

cfl_lite:
![Snipaste_2023-11-04_15-35-32](https://github.com/deus0ww/mpv-conf/assets/41094733/d442b449-c0f3-461d-bfe0-f93fa3bd290a)

**Comment by deus0ww** [comment]
I'll probably remove the lite variants soon as the standard ones are now fast enough for my needs.
