### ISSUE TITLE
Thumbnails rotated 180 degrees on my linux machine

### ISSUE THREAD

**Issue by lazydm745** [deus0ww/mpv-conf#27]
Hello,
I managed to make your brilliant configuration files work on my pc, but I noticed that the thumbnails were rotated, so I edited the Thumbnailer_Worker.lua script changing line 377 from
		add_args(args, '-noautorotate')
to
		add_args(args, '-autorotate')
and thumbnails are now correct.

**Comment by lazydm745** [comment]
edit: script is Thumbnailer_Worker.lua

**Comment by deus0ww** [comment]
what version of ffmpeg are you using?

**Comment by lazydm745** [comment]
ffmpeg version 4.4.2-0ubuntu0.22.04.1

**Comment by deus0ww** [comment]
noautorotate was added due to a recent-ish change in ffmpeg

**Comment by lazydm745** [comment]
what's your version of ffmpeg?

**Comment by deus0ww** [comment]
git head

**Comment by deus0ww** [comment]
Btw, using mpv as the thumbnailer works pretty well now. Try that, too.

**Comment by lazydm745** [comment]
is the correct setting "use_ffmpeg=no" in thumbnailer.conf?

**Comment by lazydm745** [comment]
> git head

well, pop os 22.04 LTS repo isn't cutting-edge by design, I guess

**Comment by deus0ww** [comment]
> is the correct setting "use_ffmpeg=no" in thumbnailer.conf?

Yes, or just remove it entirely.  The default is mpv.

**Comment by lazydm745** [comment]
> is the correct setting "use_ffmpeg=no" in thumbnailer.conf?

btw, I guess it is since I removed my "fix" and the thumbnails are still upright. I may be mistaken but they seem to generate faster using mpv rather than ffmpeg.

**Comment by lazydm745** [comment]
I guess I can close it here. Sorry for wasting your time, and thank you for sharing your awsome scripts and configurations!
