### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NeilTohno** [deus0ww/mpv-conf#29]
Please tell me how to use CfL+Ravu and Ravu-zoom-ar
Thanks.

```
[high_quality2]
vo=gpu-next
gpu-api=opengl
gpu-context=win
profile=gpu-hq
fbo-format=rgba16hf
vd-lavc-threads=16
#scale=ewa_lanczos
scale=ewa_lanczossharp
dscale=mitchell
#csale=ewa_lanczos
cscale=sinc
cscale-window=blackman
cscale-radius=3
glsl-shaders-append="~~/shaders/CfL_Prediction_Ravu_R2X.glsl"
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r2.hook"
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r2-rgb.hook''
```

**Comment by deus0ww** [comment]
Try setting fbo-format=rgba16f

**Comment by NeilTohno** [comment]
> Try setting fbo-format=rgba16f

Thanks.

I perfer "compute" version,
https://github.com/bjin/mpv-prescalers/tree/master/compute

```
[high_quality2]
vo=gpu-next
gpu-api=opengl
gpu-context=win
opengl-swapinterval=1
profile=gpu-hq
fbo-format=rgba16f
vd-lavc-threads=16
#scale=ewa_lanczos
scale=ewa_lanczossharp
dscale=mitchell
#csale=ewa_lanczos
cscale=sinc
cscale-window=blackman
cscale-radius=3
glsl-shaders-append="~~/shaders/CfL_Prediction_Ravu_R2X.glsl"
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r2-yuv.hook"
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r2-rgb.hook"
```

**Comment by deus0ww** [comment]
I'm going to assume this is solved.

**Comment by NeilTohno** [comment]
> I perfer "compute" version, https://github.com/bjin/mpv-prescalers/tree/master/compute
> 
> ```
> [high_quality2]
> vo=gpu-next
> gpu-api=opengl
> gpu-context=win
> opengl-swapinterval=1
> profile=gpu-hq
> fbo-format=rgba16f
> vd-lavc-threads=16
> #scale=ewa_lanczos
> scale=ewa_lanczossharp
> dscale=mitchell
> #csale=ewa_lanczos
> cscale=sinc
> cscale-window=blackman
> cscale-radius=3
> glsl-shaders-append="~~/shaders/CfL_Prediction_Ravu_R2X.glsl"
> glsl-shaders-append="~~/shaders/ravu-zoom-ar-r2-yuv.hook"
> glsl-shaders-append="~~/shaders/ravu-zoom-ar-r2-rgb.hook"
> ```
> 
> ![01](https://private-user-images.githubusercontent.com/28284594/303958840-421baab7-46d8-43d7-bf05-8d1842f1a7dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3Mzg5OTAsIm5iZiI6MTcwNzczODY5MCwicGF0aCI6Ii8yODI4NDU5NC8zMDM5NTg4NDAtNDIxYmFhYjctNDZkOC00M2Q3LWJmMDUtOGQxODQyZjFhN2RjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDExNTEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjI3NjUwNDZkNjhhMDhjMTBmOTg3YzcyZDZlMGI0MWE0N2VjZTZiYjhmMTllYjRhNzBmYjM5MDA5Y2EyODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uSM9QUX_XWXyNypwLtrk3dX8cJJVGLLvzScE2x7GjIo)
> 
> [1.zip](https://github.com/deus0ww/mpv-conf/files/14234654/1.zip)

Unknow shader, what is that?

**Comment by deus0ww** [comment]
https://code.videolan.org/videolan/libplacebo/-/issues/166

**Comment by NeilTohno** [comment]
> It's a bug within libplacebo: https://code.videolan.org/videolan/libplacebo/-/issues/166

Thank you.
