### ISSUE TITLE
Lots of repetitive errors reported by the console

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#3]
Tested by win10

`[thumbnailer_worker] -timelimit not implemented on this OS`

<img src="https://p.sda1.dev/0/a7512f79f589601135e110e0eed8a550/Snipaste_2020-12-16_15-10-27.jpg" />

**Comment by deus0ww** [comment]
This should be fixed but I can't test on Windows. If not, delete this line:

https://github.com/deus0ww/mpv-conf/blob/eabe85fe130457a53ccfc1e0f9c8a1e66dbe7aa2/scripts/Thumbnailer_Worker.lua#L374

**Comment by hooke007** [comment]
Thx, It works perfectly.
