### ISSUE TITLE
Reloaded videos won't show thumbnails

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#4]
Tested on win10
It seems it can just generate the thumbnails and show them correctly for the first time. If I reload the video again, the thumbs won't appear and I can see the similar information (in the log) which is reported by Console.

`[Thumbnailer] A subdirectory or file ~~/thumbnail_cache\Secrets - OneRepublic (Cover by Tiffany Alvord & The Piano Guys) already exists.
[Thumbnailer] Subprocess cmd failed. | Status: 1 | MPV Error: n/a | Subprocess Error: _ | Stdout: _ | Stderr: _ 
[Thumbnailer] Subprocess cmd failed. | Status: 1 | MPV Error: n/a | Subprocess Error: _ | Stdout: _ | Stderr: _ `

Line 942：[mpv.log](https://github.com/deus0ww/mpv-conf/files/5704380/mpv.log)

**Comment by deus0ww** [comment]
I may have fixed this but, again, untested on Windows.

**Comment by hooke007** [comment]
It works.
