### ISSUE TITLE
strange bahaviour about Thumbnailer worker

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#5]
Tested on win10
If I load a file by MPV，it cannot work properly.
![Snipaste_2020-12-21_14-40-10-tuya](https://user-images.githubusercontent.com/41094733/102747682-a6102580-439b-11eb-8d99-fd72a4a2a599.jpg)

If I open the mpv firstly, then drag the file into the window. It works.

**Comment by deus0ww** [comment]
In the thumbnail cache folder for that file, there should be #####.log files. Please post one or a few of those.

**Comment by hooke007** [comment]
[00225.bgra.log](https://github.com/deus0ww/mpv-conf/files/5722807/00225.bgra.log)

**Comment by deus0ww** [comment]
Are you piping the output of 'ffmpeg -i test.mkv -pix_fmt yuvj420p output' to mpv?

**Comment by hooke007** [comment]
> Are you piping the output of 'ffmpeg -i test.mkv -pix_fmt yuvj420p output' to mpv?

No, that was just the file name.

Another example:
[01064.bgra.log](https://github.com/deus0ww/mpv-conf/files/5722830/01064.bgra.log)

**Comment by deus0ww** [comment]
Please send me the mpv logs from when it works and when it doesn't.

**Comment by hooke007** [comment]
> Please send me the mpv logs from when it works and when it doesn't.
[mpv.log](https://github.com/deus0ww/mpv-conf/files/5723103/mpv.log)
==========================================
[error mpv.log](https://github.com/deus0ww/mpv-conf/files/5723105/error.mpv.log)
[error 00010.bgra.log](https://github.com/deus0ww/mpv-conf/files/5723106/error.00010.bgra.log)

**Comment by deus0ww** [comment]
Try setting these in thumbnailer.conf
use_ffmpeg=yes
prefer_ffmpeg=yes

The mpv thumbnail encoder seems to be broken (I don't why it would use that in the first place...).

**Comment by hooke007** [comment]
> Try setting these in thumbnailer.conf
> use_ffmpeg=yes
> prefer_ffmpeg=yes
> 
> The mpv thumbnail encoder seems to be broken (I don't why it would use that in the first place...).

two settings are always on in my conf

**Comment by deus0ww** [comment]
If that's the case, it would only fallback to mpv if ffmpeg is not found. Is ffmpeg in your PATH?

**Comment by hooke007** [comment]
Eh...it solves, but why?
The lua file said it can use the FFMPEG which is in the same  of mpv.exe, so when I open the mpv first and drag into the files, it can use the ffmpeg (in the same directory). However, when I open the video directly, it cannot use the ffmpeg (in the same directory).

**Comment by deus0ww** [comment]
I can only assume that the current working directory is different depending on how mpv is launched. My knowledge of how PATH works on windows is limited. I would start by adding the path to the mpv folder to the PATH variable in Window's system environment (Control Panel -> System -> something something...).

**Comment by hooke007** [comment]
Okay, that seems to be the solution.
Or will it be possible that add the config in the lua to locate the directory of FFMPEG?

**Comment by deus0ww** [comment]
The easiest way to fix this is to add ffmpeg to your path so it can be executed from anywhere.

https://www.google.com/search?q=windows+add+path

**Comment by hooke007** [comment]
> The easiest way to fix this is to add ffmpeg to your path so it can be executed from anywhere.

LoL, I know that way. Just want to make it portable for everywhere (my mpv is usually placed in the usb) that I need not modify other settings of different computers.  :-)

**Comment by deus0ww** [comment]
I added an option for this.
