### ISSUE TITLE
Thumbnailer don't auto delete thumbnail

### ISSUE THREAD

**Issue by zhongfly** [deus0ww/mpv-conf#6]
Test on win 10 with mpv 0.33
`auto_delete=1` or `auto_delete=2` in thumbnailer.conf don't work.Thumbnail still in cache dir.

**Comment by deus0ww** [comment]
Please post log. [https://mpv.io/manual/master/#options-log-file](https://mpv.io/manual/master/#options-log-file)

**Comment by zhongfly** [comment]
`auto_delete=2`
```
Exiting... (Quit)
[Thumbnailer] Deleting Dir: C:\Users\shadows\AppData\Local\Temp\Thumbnailer\[Airota][Gochuumon wa Usagi Desuka？ BLOOM][01][1080p AVC AAC][
Starting subprocess failed: init
[Thumbnailer] Deleting Dir: C:\Users\shadows\AppData\Local\Temp\Thumbnailer
Starting subprocess failed: init
```
[mpv.log](https://github.com/deus0ww/mpv-conf/files/5742108/mpv.log)

**Comment by deus0ww** [comment]
Can you test with a file that only have alphanumeric characters in the name?

**Comment by zhongfly** [comment]
test.mkv
same problem
```
[Thumbnailer] Deleting Dir: C:\Users\shadows\AppData\Local\Temp\Thumbnailer\test
Starting subprocess failed: init
[Thumbnailer] Deleting Dir: C:\Users\shadows\AppData\Local\Temp\Thumbnailer
Starting subprocess failed: init
```
[mpv.log](https://github.com/deus0ww/mpv-conf/files/5742112/mpv.log)

**Comment by deus0ww** [comment]
Try again, I may have fixed it (but completely untested on Windows).

**Comment by zhongfly** [comment]
no fail but not delete thumbnail
so I changed cache dir but still not delete thumbnail
```
Exiting... (Quit)
[Thumbnailer] Deleting Dir: D:\Thumbnailer\test
```
[mpv.log](https://github.com/deus0ww/mpv-conf/files/5742157/mpv.log)

**Comment by deus0ww** [comment]
Try again? (Sorry, I can't test on Windows...)

**Comment by zhongfly** [comment]
Thanks,It work!
