### ISSUE TITLE
Thumbnails are transparent without ffmpeg

### ISSUE THREAD

**Issue by qazesz1** [deus0ww/mpv-conf#7]
Hello,

I'm using mpv 0.33 on windows 10. Once `use_ffmpeg=no prefer_ffmpeg=no` were configured the thumbnails became transparent. 
![2021-01-05 135501](https://user-images.githubusercontent.com/30799958/103611647-ac86cb80-4f5d-11eb-81f0-d339174403f1.jpg)

It would be annoyed on condition that ffmpeg not installed so please make a fix. Thank you!

**Comment by deus0ww** [comment]
This should be fixed. Please test.

**Comment by qazesz1** [comment]
It's normal now.
