### ISSUE TITLE
Limitation of the directory?

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#8]
![Snipaste_2021-01-29_02-17-25](https://user-images.githubusercontent.com/41094733/106182193-785b9f00-61d9-11eb-977e-847ad1b18aaa.jpg)
[mpv.log](https://github.com/deus0ww/mpv-conf/files/5889336/mpv.log)
It seems that Thumbnailer do not support the long words of the directory.

**Comment by deus0ww** [comment]
Yeah, it's probably something to do with path length or character encoding. On Windows, there's no fallback to deal with this.

**Comment by deus0ww** [comment]
Try again? I may have fixed it.

**Comment by hooke007** [comment]
Yeah, it works.
=============
Another issue: (I don't think it is a bug) If I close the window, it won't immediately shut down when it was creating the thumbnails. It seems wait for 1 or 2 seconds, do you know why?

**Comment by deus0ww** [comment]
It's waiting for external ffmpeg/mpv processes to finish thumbnails that already started processing before exiting. Also, generating the thumbnails is quite an intense process (CPU wise).

**Comment by hooke007** [comment]
Sorry, now it seems do not support the chinese words. (old version supported.)

Any file like 中文字符.mp4 would not generate the thumbnails.

![Snipaste_2021-01-30_20-41-29](https://user-images.githubusercontent.com/41094733/106356585-bc66b500-633b-11eb-9e79-8f59b558b3b0.jpg)

**Comment by deus0ww** [comment]
That's an expected regression. It's striping non-alphanumeric chars from the filename and, in this case, leaving an empty string. On other platforms, weird filenames get hashed. I haven't figured out how to do that on Windows yet (and Lua doesn't have a native hashing function).

**Comment by deus0ww** [comment]
I modified the previous workaround. Please test again with both files.

**Comment by hooke007** [comment]
It works fine with the samples.

Previously, it will fail and creat one .bgra file in the same directory of the video. what is that file?
[unknown file.zip](https://github.com/deus0ww/mpv-conf/files/5898116/unknown.file.zip)

**Comment by deus0ww** [comment]
Nice. This will have to do for now.  *.bgra are raw thumbnail files. They're supposed to be in the thumbnail cache dir.
