### ISSUE TITLE
[Thumbnailer_Worker] errors and broken thumbnails

### ISSUE THREAD

**Issue by hooke007** [deus0ww/mpv-conf#9]
Only if I use the `ffmpeg` and `AVC.YUV444P10` sources, it will happen.

![Snipaste_2021-02-23_19-42-47-ty](https://user-images.githubusercontent.com/41094733/108839170-ab922200-760f-11eb-8730-af0d7399a256.jpg)

And there is no log file in the temp thumbnailer folder.

**Comment by deus0ww** [comment]
This is either an issue with ffmpeg or your file. Do other YUV444P10 files have the same issue? I would try upgrading ffmpeg, first.

**Comment by hooke007** [comment]
It is weird, it can be played normally by ffplay. Now I can not find the other AVC.YUV444P10 can work.

**Comment by hooke007** [comment]
I got some ideas from the related video rippers, they said that some special parameters will lead to the situation. So I consider it a special video.
